# Generated by Django 4.2.3 on 2023-07-11 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_psot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Psot',
            new_name='Post',
        ),
    ]
