# Generated by Django 4.2.3 on 2023-07-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_liker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uername', models.CharField(max_length=100)),
                ('post_id', models.CharField(max_length=100)),
            ],
        ),
    ]
